// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"
)

type Book struct {
	ID        int32
	Name      string
	CreatedAt time.Time
}

type Entry struct {
	ID        int32
	BookID    int32
	Content   string
	Type      string
	Key       sql.NullString
	CreatedAt time.Time
}
